### ISSUE TITLE
Scrolling Gallery 

### ISSUE THREAD

**Issue by diegomey** [CosmicCritters/cosmic-critters#10]
## **Story**

Scrolling gallery for critter 

### Acceptance Criteria

![Screenshot (gallery)](https://user-images.githubusercontent.com/69913029/139783808-a00eabae-0d60-4753-a865-908261d3421b.png)

**Comment by martinsvinicius** [comment]
done 🧐

**Comment by CosmicCritters** [comment]
@martinsvinicius https://codesandbox.io/s/infinite-carousel-example-ifebt?file=/package.json
