### ISSUE TITLE
Taylor + Logos Top Hero Area 

### ISSUE THREAD

**Issue by diegomey** [CosmicCritters/cosmic-critters#17]
## **Story**

As a as resize the Taylor + Logos as too far to the left, and does not scale down when closer to the logo, 

### Acceptance Criteria

Limit div max view width and with more padding or % of div section filter so it scales down. 

### Resources:

![Screenshot (112)](https://user-images.githubusercontent.com/69913029/139964373-264ad995-14c8-4535-b6ae-f4265d3546c5.png)

### Notes

**Comment by martinsvinicius** [comment]
I think this issue has already been resolved.
