### ISSUE TITLE
Nav Bar Size Home vs Internal

### ISSUE THREAD

**Issue by diegomey** [CosmicCritters/cosmic-critters#20]
## **Story**

As I navigate to internal pages I get a small shift in position or placement of elements - such as logo on the header/nav bar

https://sharing.clickup.com/clip/p/t2276118/24ebccd8-aa7d-4d47-bfce-40044b71d9fc/screen-recording-2021-11-02-22:12.webm?open=true

**Comment by CosmicCritters** [comment]
nav bar from internal pages has different positions than home page

**Comment by martinsvinicius** [comment]
fixed :)
