### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by CosmicCritters** [CosmicCritters/cosmic-critters#21]
## **Story**

Add Social media Links to CC page 

### Acceptance Criteria
https://www.cosmiccritters.com/

**Comment by CosmicCritters** [comment]
Footer
Header
Body
https://www.instagram.com/critterNFT/
https://twitter.com/critterNFT/
https://discord.com/invite/akyjRWwWNs

Taylor - Letter
https://twitter.com/nftaymitchell
https://instagram.com/taylormitchell.official
https://tiktok.com/@taylormitchell.official

TEAM
Pending

**Comment by CosmicCritters** [comment]
TEAM

**JOJ**
https://www.instagram.com/studiojoj/
https://twitter.com/critterNFT/

**Comment by martinsvinicius** [comment]
done
