### ISSUE TITLE
Background - Sustainability

### ISSUE THREAD

**Issue by CosmicCritters** [CosmicCritters/cosmic-critters#27]
## **Story**

Background is showing broken SVG files. 

On figma there's a color behind the svg files to hide these spaces (green)

![Screenshot (1s3)](https://user-images.githubusercontent.com/93553359/140619304-2085f1a3-31a1-49f9-9423-c7e0248d95ac.png)

### Acceptance Criteria

Adicionar um fundo verde da mesma cor do verde principal do fundo, isso ajuda a "mascarar" esses breaks do svg. 
#0F603F

### Resources:
Preview do figma esta correto - porem tem um rectangulo verde atras de cor solida:

![Screenshot (13)](https://user-images.githubusercontent.com/93553359/140619325-2ae3f287-2894-4382-b92f-b1750a236258.png)

### Notes

- lorem ipsum

**Comment by martinsvinicius** [comment]
done
