### ISSUE TITLE
Team Responsiveness Box

### ISSUE THREAD

**Issue by CosmicCritters** [CosmicCritters/cosmic-critters#34]
## **Story**

Responsive box for 3 team member

![Screenshot (13)](https://user-images.githubusercontent.com/93553359/140659673-612a773a-6def-4ca5-b143-ba00f315cda4.png)

**Comment by diegomey** [comment]
Add Links to team member: Masterbrews and Joshua

Twitter:
@masterbrewsNFT
@crypt0artist
