### ISSUE TITLE
Desktop Footer - Missing Elements

### ISSUE THREAD

**Issue by CosmicCritters** [CosmicCritters/cosmic-critters#35]
## **Story**

Missing **AND JOIN THE COMMUNITY** on Desktop  - should be hidden ONLY for mobile

![Screenshot (13)](https://user-images.githubusercontent.com/93553359/140659724-e7ee7763-b215-4078-a770-c2e185844f3d.png)

### Acceptance Criteria

![Screenshot (131111)](https://user-images.githubusercontent.com/93553359/140659719-413bf791-e2db-4994-9909-c94ec690135f.png)

**Comment by diegomey** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/69913029/140664344-2ad48607-bbca-4bf7-81f1-1f34acbe845c.png)
