### ISSUE TITLE
Sizing/Padding Partners Logo and Add Links

### ISSUE THREAD

**Issue by diegomey** [CosmicCritters/cosmic-critters#37]
## **Story**

Revise sizing and padding - vercel
![AA-Screenshot (13)](https://user-images.githubusercontent.com/69913029/140663236-b23c5ed9-3651-4cdf-bca5-ff1d4b39edb7.png)

### Acceptance Criteria
1, revise size/height
![figma-Screenshot (13)](https://user-images.githubusercontent.com/69913029/140663243-e11f13be-a0ed-4088-bfd2-c9af70a89613.png)

2. add Links (home and Sustainability page)

- https://www.onepercentfortheplanet.org/
- https://onetreeplanted.org/
- https://getchange.io/

### Resources:

- resource: [a link for that resource];

### Notes

- lorem ipsum

**Comment by martinsvinicius** [comment]
done
