### ISSUE TITLE
Newsletter Subscribe field missing [User-Story]

### ISSUE THREAD

**Issue by diegomey** [CosmicCritters/cosmic-critters#6]
## **Story**

![Screenshot (1222)](https://user-images.githubusercontent.com/69913029/139782372-aa9ee376-e3c7-4296-b502-78abdc4bfcba.png)

### Acceptance Criteria

![aa-Screenshot (1222)](https://user-images.githubusercontent.com/69913029/139782382-ab0b799f-de98-4726-a01e-c6d208b3fa7c.png)

### Notes

- CSS styles will be applied to Klaviyo Form Field

**Comment by martinsvinicius** [comment]
done
