### ISSUE TITLE
Div Layer Pop up 

### ISSUE THREAD

**Issue by diegomey** [CosmicCritters/cosmic-critters#65]
## **Story**

When the popup is activated by CONNECT YOUR WALLET (new branch) desktop
is goes behind the DIV Images.

![image](https://user-images.githubusercontent.com/69913029/143941187-4010a70d-cb27-4a60-b091-97423cb7b973.png)

- Dev will push these changes to the main for editing - we just need the popup to be on TOP of everything

**Comment by martinsvinicius** [comment]
done
