### ISSUE TITLE
Side Scrolling Buttons POD Right - Sustainability + story  Fixed

### ISSUE THREAD

**Issue by diegomey** [CosmicCritters/cosmic-critters#9]
## **Story**

Missing Scrolling Element

### Acceptance Criteria

![Screenshot (12)](https://user-images.githubusercontent.com/69913029/139783050-01a31a35-9c4c-4270-8639-df4d540d1e15.png)

![Screenshot111 (12)](https://user-images.githubusercontent.com/69913029/139783589-60f862ad-4aec-4dc6-965c-d2969d00ecbe.png)

### Notes

- see PDF attached to where left and right buttons enters the fram
[Artboard 1scrolling-buttons.pdf](https://github.com/jhortale/cosmic-critters/files/7457677/Artboard.1scrolling-buttons.pdf)
es

**Comment by CosmicCritters** [comment]
@martinsvinicius  

https://sharing.clickup.com/clip/p/t2276118/33bd4d76-7a9e-4fce-8e02-c4adaef7490d/screen-recording-2021-11-06-14:13.webm?open=true

**Comment by martinsvinicius** [comment]
done

**Comment by CosmicCritters** [comment]
Reopening since scrolling buttons are not moving

**Comment by martinsvinicius** [comment]
fixed
